### ISSUE TITLE
Safari tests fail Uncaught Error: no value passed to Element constructor

### ISSUE THREAD

**Issue by cben** [cben/mathdown#187]
https://travis-ci.org/cben/mathdown/jobs/469424338#L810
```
  1) Served site via Sauce Connect
       Safari undefined latest on macOS 10.13
         should load and render math:
     Uncaught Error: no value passed to Element constructor
      at new Element (node_modules/wd/lib/element.js:15:11)
      at Webdriver.newElement (node_modules/wd/lib/webdriver.js:44:10)
      at /home/travis/build/cben/mathdown/node_modules/wd/lib/callbacks.js:156:24
      at /home/travis/build/cben/mathdown/node_modules/wd/lib/callbacks.js:101:7
      at /home/travis/build/cben/mathdown/node_modules/wd/lib/webdriver.js:185:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:186:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1163:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1085:12)
      at endReadableNT (_stream_readable.js:978:12)
      at _combinedTickCallback (inernal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by cben** [comment]
Debugging inside `wd`...
During `waitForElementByCss(".MathJax_Display",30000)`, I'm seeing this data inside `elementsCallback`:
```
          > CALL: elements("css selector",".MathJax_Display")
--- {"status": 0, "state": "success", "sessionId": null, "value": [], "class": "org.openqa.selenium.remote.Response"}

          > CALL: elements("css selector",".MathJax_Display")
--- {"status": 0, "state": "success", "sessionId": null, "value": [{"element-6066-11e4-a52e-4f735466cecf": "node-68AB553D-A013-4307-8FFF-080356B46693"}], "class": "org.openqa.selenium.remote.Response"}
```
which fails because expected `obj.values[i].ELEMENT` doesn't exist.

Turns out this `element-UUID` key is a _fixed_ key, specified by current spec https://w3c.github.io/webdriver/#dfn-web-elements

For comparison, with Firefox, data contains `ELEMENT` like expect:
```
          > CALL: elements("css selector",".MathJax_Display")
--- {"status": 0, "state": null, "value": [{"ELEMENT": "0"}], "sessionId": "db5c2553d6364e45b1bc5c4950eb1d51", "hCode": 16788021, "class": "org.openqa.selenium.remote.Response"}
```
this matches older spec https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelement

(branch adding debug prints: https://github.com/cben/wd/commit/DEBUG-elements)

**Comment by cben** [comment]
Fixed by https://github.com/admc/wd/pull/574 :tada:, not yet released, will upgrade wd to master
